// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'latest_posts_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_LatestPostsDto _$$_LatestPostsDtoFromJson(Map<String, dynamic> json) =>
    _$_LatestPostsDto(
      jobId: _stringFromJson(json['JobID']),
      jobNo: _stringFromJson(json['JobNo']),
      employerId: _stringFromJson(json['EmployerID']),
      title: _stringFromJson(json['Title']),
      positionId: _stringFromJson(json['PositionID']),
      jobCategoryId: _stringFromJson(json['JobCategoryID']),
      jobCategoryName: _stringFromJson(json['JobCategoryName']),
      industryId: _stringFromJson(json['IndustryID']),
      workingStateId: _stringFromJson(json['WorkingStateID']),
      workingTownshipId: _stringFromJson(json['WorkingTownshipID']),
      status: _stringFromJson(json['Status']),
      expiredOn: _stringFromJson(json['ExpiredOn']),
      employmentType: _stringFromJson(json['EmploymentType']),
      salaryRange: _stringFromJson(json['SalaryRange']),
      salaryType: _stringFromJson(json['SalaryType']),
      active: json['Active'] as bool?,
      createdBy: _stringFromJson(json['CreatedBy']),
      createdOn: _stringFromJson(json['CreatedOn']),
      modifiedBy: _stringFromJson(json['ModifiedBy']),
      modifiedOn: _stringFromJson(json['ModifiedOn']),
      lastAction: _stringFromJson(json['LastAction']),
      jobScope: _stringFromJson(json['JobScope']),
      educationRequirement: _stringFromJson(json['EducationRequirement']),
      experiencedLevel: _stringFromJson(json['ExperiencedLevel']),
      additionalQuestionsAnswer:
          _stringFromJson(json['AdditionalQuestionsAnswer']),
      coverLetter: _stringFromJson(json['CoverLetter']),
      employerNo: _stringFromJson(json['EmployerNo']),
      companyName: _stringFromJson(json['CompanyName']),
      website: _stringFromJson(json['Website']),
      email: _stringFromJson(json['Email']),
      facebook: _stringFromJson(json['Facebook']),
      phoneNumber: _stringFromJson(json['PhoneNumber']),
      address: _stringFromJson(json['Address']),
      positionName: _stringFromJson(json['PositionName']),
      industryName: _stringFromJson(json['IndustryName']),
      stateName: _stringFromJson(json['StateName']),
      townshipName: _stringFromJson(json['TownshipName']),
      createdByCode: _stringFromJson(json['CreatedByCode']),
      modifiedByCode: _stringFromJson(json['ModifiedByCode']),
      uploadCompanyLogo: _stringFromJson(json['UploadCompanyLogo']),
      uploadCompanyCoverphoto: _stringFromJson(json['UploadCompanyCoverphoto']),
      accountId: _stringFromJson(json['AccountID']),
      viewCount: _stringFromJson(json['ViewCount']),
      applicantCounts: _stringFromJson(json['ApplicantCounts']),
      workaddress: _stringFromJson(json['Workaddress']),
      gender: _stringFromJson(json['Gender']),
      benefits: _stringFromJson(json['Benefits']),
      careerOpportunities: _stringFromJson(json['CareerOpportunities']),
      highlights: _stringFromJson(json['Highlights']),
      recruiterActive: _stringFromJson(json['RecruiterActive']),
      postTime: _stringFromJson(json['PostTime']),
      employmentTypeHighLightColor:
          _stringFromJson(json['EmploymentTypeHighLightColor']),
    );

Map<String, dynamic> _$$_LatestPostsDtoToJson(_$_LatestPostsDto instance) =>
    <String, dynamic>{
      'JobID': instance.jobId,
      'JobNo': instance.jobNo,
      'EmployerID': instance.employerId,
      'Title': instance.title,
      'PositionID': instance.positionId,
      'JobCategoryID': instance.jobCategoryId,
      'JobCategoryName': instance.jobCategoryName,
      'IndustryID': instance.industryId,
      'WorkingStateID': instance.workingStateId,
      'WorkingTownshipID': instance.workingTownshipId,
      'Status': instance.status,
      'ExpiredOn': instance.expiredOn,
      'EmploymentType': instance.employmentType,
      'SalaryRange': instance.salaryRange,
      'SalaryType': instance.salaryType,
      'Active': instance.active,
      'CreatedBy': instance.createdBy,
      'CreatedOn': instance.createdOn,
      'ModifiedBy': instance.modifiedBy,
      'ModifiedOn': instance.modifiedOn,
      'LastAction': instance.lastAction,
      'JobScope': instance.jobScope,
      'EducationRequirement': instance.educationRequirement,
      'ExperiencedLevel': instance.experiencedLevel,
      'AdditionalQuestionsAnswer': instance.additionalQuestionsAnswer,
      'CoverLetter': instance.coverLetter,
      'EmployerNo': instance.employerNo,
      'CompanyName': instance.companyName,
      'Website': instance.website,
      'Email': instance.email,
      'Facebook': instance.facebook,
      'PhoneNumber': instance.phoneNumber,
      'Address': instance.address,
      'PositionName': instance.positionName,
      'IndustryName': instance.industryName,
      'StateName': instance.stateName,
      'TownshipName': instance.townshipName,
      'CreatedByCode': instance.createdByCode,
      'ModifiedByCode': instance.modifiedByCode,
      'UploadCompanyLogo': instance.uploadCompanyLogo,
      'UploadCompanyCoverphoto': instance.uploadCompanyCoverphoto,
      'AccountID': instance.accountId,
      'ViewCount': instance.viewCount,
      'ApplicantCounts': instance.applicantCounts,
      'Workaddress': instance.workaddress,
      'Gender': instance.gender,
      'Benefits': instance.benefits,
      'CareerOpportunities': instance.careerOpportunities,
      'Highlights': instance.highlights,
      'RecruiterActive': instance.recruiterActive,
      'PostTime': instance.postTime,
      'EmploymentTypeHighLightColor': instance.employmentTypeHighLightColor,
    };
